title: Hello, ETL world!
description: > # this means to ignore newlines until "baseurl:"
  Data Engineering Blog.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://etlgirl.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: ETL Girl # add your name
author-img: etl-girl.jpg # add your photo
about-author: Data Engineering Blog. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: pumpkin27 # add your Github handle
social-linkedin: klaudia-szpyrka/ # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: etlgirl-github-io # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
